// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Farmhash.Sharp")]
[assembly: AssemblyProductAttribute("Farmhash.Sharp")]
[assembly: AssemblyDescriptionAttribute("Port of Google's farm hash algorithm")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
